name: message_box
description: "A mini library with action message widget"
version: 0.0.1
homepage: https://github.com/prokhor-andrew/message_box

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
